### ISSUE TITLE
Auto refresh to show new question 

### ISSUE THREAD

**Issue by timedilation** [swsnu/swpp17-team6#27]
User have to refresh website after post question to see it.
Make auto refresh right after posting question.

**Comment by HS-YN** [comment]
Resolved [here](https://github.com/swsnu/swpp17-team6/commit/a7d2871a50719e36e97eb23897271d8c32e42c24). By only refreshing url and not refreshing the view, new questions are smoothly added.
Also, auto refreshing answer list has been implemented. But since there was difficulties for redirecting the tab, I had no choice but to literally refresh. (This refreshing policy might bother user, in my opinion.)

**Comment by seonghoon247** [comment]
Reviewed. The code seems fine and the app performs as expected. However, I think the problem Heeseung mentioned regarding refreshing tabs should be resolved in the form of "enhancement".

**Comment by HS-YN** [comment]
@seonghoon247 Then why don't you post an issue about this?

**Comment by seonghoon247** [comment]
@HS-YN I just posted an issue regarding this with enhancement label :)
