### ISSUE TITLE
Notification about migrating model

### ISSUE THREAD

**Issue by wogur0602** [swsnu/swpp17-team6#57]
When you change the model(especially adding some fields) and migrate it, you can see the message like
* You are trying to add a non-nullable filed _'field name'_ to _'app name'_ without a default; we can't do that (the database needs something to populate existing rows)...

If the field is primitive type like int, boolean, you should set default value like
 * _'field name'_ = models.IntegerField (default = 0)

If not, like OneToOneField, you should _**remove all DB**_ of app with admin account.

**Comment by HS-YN** [comment]
@wogur0602 Even though removing all DB is the most feasible shortcut in the situation that you've described, but after deployment, it is quite risky to remove all database.
It is perfectly fine to do so before deployment, but after deployment, using incremental update as discussed in lecture, rather than naive update, would be desirable in my opinion.
