### ISSUE TITLE
Make loading question faster

### ISSUE THREAD

**Issue by timedilation** [swsnu/swpp17-team6#85]
1. Get answers
a) for all question when loading tab
b) for one question when clicking it

2. Get questions from backend
a) only for limited number. When user reads all questions(scroll down), request next questions.
b) for all. Show limited number of questions at once in question list.

**Comment by seonghoon247** [comment]
@timedilation 
**1.**
I also thought about 1 - b) since we initially show the questions in the collapsed form.
However, if we go with 1-b), we might have to send HTTP request every time a question is expanded.
Or, I think we could create an additional variable to keep track of whether a question has already received answers from backend or not.

**2.**
I am not sure which method is better.
a) would decrease the the load of data `getQuestion()` http request needs to send, but it might be hard to keep track of next n questions since new questions can be added to backend before scroll down is executed. (Might cause concurrency unless keep track of a pointer(?) that directs to the last question sent to frontend)

b) seems okay at the time being, but as user's list of answered questions and asked questions pile up, loading the two tabs might get more costly.

Any Suggestions?

**Comment by wogur0602** [comment]
@timedilation 
1. I think b) is better than a) because of the initial loading time of the page. Getting answers  of all question is quite heavy task.
As @seonghoon247 said, if we make some cache (queue) for some recently shown answers then we don't need to worry about latency.
However, I don't know there's meaningful gap implementing cache or not because I think there's small # of answers binded with a single question. (Light HTTP communication)
2. I think b) is better. If we set policy as a), we should cache questions in the backend because the frontend should not get overlapped questions.
There's way to cache question in backend: one-to-many, but it takes too much overhead. (we should update db for each updates)
Also a) has problem about loading questions: what question we should load in second request? Latest one? or Stick to order of previous questions?


+α Why don't we set string length limit to question and answer?

**Comment by timedilation** [comment]
1. Then, let's choose 1-b) With flag attached to question which tells whether the answer is loaded or not. We currently make Question list in type : [question, boolean, answerlist]. Add one more boolean into this. If boolean is false, load answers and push it in to Question list(on answer list), if it is true, load question(and answers) as we do currently.

2. @HS-YN I agree with difficulties of storing information in backend.. but when there are too much questions in recentQuestion, like one thousand, loading those will take so much time.

How about we request recentQuestion with time information? When User tries to see more questions, send last question's time to backend, and backend send back 10(ex) questions after that time.


Setting string length limit is good.
What about 
Answer : 150 , Question: 250 ? (bytes)

**Comment by timedilation** [comment]
decide to fetch more questions when user read all and request more

**Comment by HS-YN** [comment]
In current service, all questions are loaded at once without bugs as long as the conditions are met. Since partial loading is the problem of enhancement (not implementation), I will temporarily set this issue as closed.
