### ISSUE TITLE
invalid city label added to page

### ISSUE THREAD

**Issue by timedilation** [swsnu/swpp17-team6#89]
At signup, after you fill country, province, type city name wrong and press add,
it shows invalid city name alert but also adds label for that.

**Comment by seonghoon247** [comment]
We have detected this incident while preparing for the QA,  
but at that time we left it as it was since the user still cannot add that label to the list of location tags
and thus, no wrong city name is actually stored or sent to backend server.

However, I think resolving this issue is still important considering the UI/UX.

**Comment by HS-YN** [comment]
(Resolved in deployment version)
